export const path = {
    home: '/',
    register: '/register',
    login: '/login',
    forgotPassword: '/forgotPassword',
    productList: '/productList',
    news: '/news',
    introduce: '/introduce',
    contact: '/contact',
    cart: '/cart',
    productDetail: ':nameId',
    checkout: '/checkout',
    checkoutAddress: '/checkout/address',
    checkoutPayment: '/checkout/payment',
    checkoutThankYou: '/checkout/thankyou',
    account: '/account',
    accountOder: '/account/oder/:nameId',
    changePassword: '/account/changepassword',
    updateProfile: '/account/updateprofile'
}
